Compress images using sharp
NationalCentreTruthReconciliation/Secure-Record-Transfer pull request #264
Opened 2024-12-10 19:39 UTC by yenaing-oo

An alternative method to compressing images, that does not rely on webpack.

2024-12-10 21:34 UTC, yenaing-oo commented
Here is a comparison of the original image file sizes vs the compressed ones:

Original
![image](https://github.com/user-attachments/assets/b81e32d7-8bef-422a-b813-2e4e8728484d)

Compressed
![image](https://github.com/user-attachments/assets/533067c4-95ce-4746-bb6e-e5a328f91981)

2024-12-10 21:57 UTC, danloveg requested changes
I like this, it's simple and works in development and production.

I also like if we accidentally forget to link to the `.webp` file that the original file will still load fine.

2024-12-10 21:57 UTC, danloveg commented on scripts/compress_images.js
Nice, you wrote this in Javascript!

I do have a comment, can you add a console.log at the start and end so there's more feedback in the logs about when this script starts and ends?

2024-12-11 14:41 UTC, yenaing-oo commented on scripts/compress_images.js
Absolutely.

Resolved by https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/pull/264/commits/6086edc73c6cd7fb157737e36fddb86a3c82459e

2024-12-11 15:21 UTC, danloveg submitted a review, later dismissed
This all looks great.

This opens the door to migrate this code to a custom webpack plugin. For the time being, though, there's no need to do anything more complex than this.

2024-12-11 15:23 UTC, danloveg approved these changes

2024-12-11 15:23 UTC, merged