Add protection from clicking away from form
NationalCentreTruthReconciliation/Secure-Record-Transfer pull request #288
Opened 2024-12-19 23:14 UTC by yenaing-oo

Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/283

2024-12-19 23:20 UTC, yenaing-oo commented
TODO:
- Do not place event listeners on non-navigational links (`tel:` and `mailto:`)
- Add event listener for `beforeunload` event for when user closes tab or browser

2024-12-27 04:59 UTC, danloveg requested changes
Really nice job on the styling of the modal, it looks awesome!

There are a few more places that require the `non-nav-link` class:

- https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/blob/ce6554c58422c90d82df83a87d2c27fb64ce9cc1/bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_rights.html#L7
  - This is the link a user would click to explain the different types of rights.
- https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/blob/ce6554c58422c90d82df83a87d2c27fb64ce9cc1/bagitobjecttransfer/recordtransfer/templates/recordtransfer/header.html#L66
  - This is the mobile menu button.
- https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/blob/ce6554c58422c90d82df83a87d2c27fb64ce9cc1/bagitobjecttransfer/recordtransfer/templates/recordtransfer/header.html#L71
  - This is the mobile *close* menu button.

Regarding the form not submitting, try cherry-picking this commit: a80d7d5603a6b46f3c4881421fc99b7dd50fdb68.

2024-12-27 17:28 UTC, yenaing-oo commented
Thanks for the feedback!

I've added the missing classes here: https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/pull/288/commits/2cb265388d9c47c975277dbf584239838d143a71.

The modal is now responsive for screen sizes of width <= 800px: https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/pull/288/commits/93e75c6c768f42a024a2fbe1c0a183ad0ee2b21e

2025-01-05 22:54 UTC, danloveg requested changes
One last little thing and this is good to go!

2025-01-05 22:54 UTC, danloveg commented on bagitobjecttransfer/recordtransfer/static/recordtransfer/css/base/modal.css
> +
The font is a little too small when the screen is under 800px wide. Without the `font-size` rule the modal size is still manageable.

```suggestion
    .modal-content {
        max-width: 80%;
        padding: 15px;
    }
```

This is without `font-size: small;` (i.e., with my change incorporated):

![Screenshot 2025-01-05 165325](https://github.com/user-attachments/assets/e62dd1d2-beec-4844-9486-c1e4f593fa8e)

2025-01-06 00:00 UTC, yenaing-oo commented on bagitobjecttransfer/recordtransfer/static/recordtransfer/css/base/modal.css
> +
I agree, I've made the change here https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/pull/288/commits/47ba9410b3930de358c26d921b193f4f61174f67

2025-01-06 00:17 UTC, yenaing-oo commented
Just did a rebase and fixed a couple of merge conflicts.

2025-01-06 00:52 UTC, danloveg approved these changes
🚀!

2025-01-06 00:52 UTC, merged